repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.56.1
    hooks:
      - id: swiftlint
        name: SwiftLint for MusicSpot v2
        entry: swiftlint lint --config "iOS/.swiftlint.yml" "iOS/MusicSpot/"
        language: swift
        types: [swift]
        always_run: true
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.54.3
    hooks:
      - id: swiftformat
        name: SwiftFormat for MusicSpot v2
        entry: swiftformat --config "iOS/.swiftformat" "iOS/MusicSpot/"
        language: swift
        types: [swift]
        always_run: true
